const testDatas = [
    [
        [
            "Brand",
            "Region",
            "Year",
            "Model Type",
            "Sales",
            "Costs",
            "Market Share"
        ],
        [
            "BMW",
            "Asia",
            2015,
            "Sedan",
            6000,
            12000,
            0.1
        ],
        [
            "BMW",
            "Asia",
            2015,
            "SUV",
            10000,
            15000,
            0.07
        ],
        [
            "BMW",
            "Asia",
            2016,
            "Sedan",
            10000,
            11000,
            0.12
        ],
        [
            "BMW",
            "Asia",
            2016,
            "SUV",
            12000,
            16000,
            0.08
        ],
        [
            "BMW",
            "Asia",
            2017,
            "Sedan",
            13000,
            13000,
            0.15
        ],
        [
            "BMW",
            "Asia",
            2017,
            "SUV",
            15000,
            18000,
            0.1
        ],
        [
            "BMW",
            "Europe",
            2015,
            "Sedan",
            6000,
            14000,
            0.25
        ],
        [
            "BMW",
            "Europe",
            2015,
            "SUV",
            11000,
            18000,
            0.18
        ],
        [
            "BMW",
            "Europe",
            2016,
            "Sedan",
            10000,
            13000,
            0.28
        ],
        [
            "BMW",
            "Europe",
            2016,
            "SUV",
            13000,
            19000,
            0.2
        ],
        [
            "BMW",
            "Europe",
            2017,
            "Sedan",
            13000,
            15000,
            0.32
        ],
        [
            "BMW",
            "Europe",
            2017,
            "SUV",
            18000,
            20000,
            0.23
        ],
        [
            "Toyota",
            "Asia",
            2015,
            "Sedan",
            18000,
            10000,
            0.3
        ],
        [
            "Toyota",
            "Asia",
            2015,
            "SUV",
            40000,
            15000,
            0.2
        ],
        [
            "Toyota",
            "Asia",
            2016,
            "Sedan",
            55000,
            11000,
            0.35
        ],
        [
            "Toyota",
            "Asia",
            2016,
            "SUV",
            45000,
            16000,
            0.25
        ],
        [
            "Toyota",
            "Asia",
            2017,
            "Sedan",
            60000,
            12000,
            0.4
        ],
        [
            "Toyota",
            "Asia",
            2017,
            "SUV",
            50000,
            18000,
            0.3
        ],
        [
            "Toyota",
            "Europe",
            2015,
            "Sedan",
            70000,
            13000,
            0.5
        ],
        [
            "Toyota",
            "Europe",
            2015,
            "SUV",
            60000,
            18000,
            0.4
        ],
        [
            "Toyota",
            "Europe",
            2016,
            "Sedan",
            75000,
            12000,
            0.55
        ],
        [
            "Toyota",
            "Europe",
            2016,
            "SUV",
            65000,
            19000,
            0.45
        ],
        [
            "Toyota",
            "Europe",
            2017,
            "Sedan",
            80000,
            14000,
            0.6
        ],
        [
            "Toyota",
            "Europe",
            2017,
            "SUV",
            70000,
            20000,
            0.5
        ]
    ],
]
export default testDatas;